### ISSUE TITLE
Resource pack

### ISSUE THREAD

**Issue by Stumblinbear** [InventivetalentDev/MineRender#10]
I've searched through the docs and am unable to figure out how to use a custom resource pack. It doesn't seem to be documented very well. I either need to be able to pass in a list of models and base64/url textures, or set up the URL endpoint for a model/texture (though I would prefer the former, as it fits better with my use case).

Could you provide any insight on how the custom resource pack system functions?

**Comment by InventivetalentDev** [comment]
To use resource packs, you simply pass the [`assetRoot` option when constructing](https://docs.minerender.org/class/src/model/index.js~ModelRender.html#instance-constructor-constructor) a ModelRenderer. This should be a path to an extracted resource pack.  

This is briefly mentioned at the bottom of the MineRender website, but is quite easy to miss ^^ 
> {
    centerCubes: false,     // Center the cube's rotation point
    assetRoot: "https://assets.mcasset.cloud/1.13"    // Root location to get assets from - change if you want to use e.g a resource pack
};   

You can also check out the javascript for the showcases, where this is also used: https://github.com/InventivetalentDev/MineRender/blob/master/js/main.js#L298

**Comment by Stumblinbear** [comment]
Aha. So I don't need any special formatting of the pack, just a URL that will navigate the structure of the pack from the "natural root" of the pack zip?

I'll poke at that and get back to you

**Comment by Stumblinbear** [comment]
Hm. It looks like it works, however is there a way to directly pass JSON and textures as parameters in the render function? It would reduce complexity in my system a whole lot.

**Comment by InventivetalentDev** [comment]
> is there a way to directly pass JSON and textures as parameters 
Not really.  
Feel free to check the [ModelRender source](https://github.com/InventivetalentDev/MineRender/blob/master/src/model/index.js) to maybe figure out a way that suits your needs, but the whole thing is based around minecraft's existing resource structure to make it easy to get started.

**Comment by Stumblinbear** [comment]
Rats. I may make some edits, then, as emulating an entire resource pack is a bit much for my use case. Thanks for the assistance!
