### ISSUE TITLE
Recipe is not displayed correctly

### ISSUE THREAD

**Issue by NightlandDriver** [InventivetalentDev/MineRender#104]
Hey, how do I get it with the recipe to display it like without a ResourcePack?
I found this for the inventory, but it doesn’t seem to be the case for the recipes.

As soon as I specify Conquest as a texture pack it looks like on the screenshot.
[https://ibb.co/N6qwc0j](https://ibb.co/N6qwc0j)

Source Code:
[https://pastebin.com/k1zu6bPZ](https://pastebin.com/k1zu6bPZ)

**Comment by NightlandDriver** [comment]
I have another problem, I would like to host the recipes I want to present locally on the server, but now I get the following error with the following code.

[Error](https://pastebin.com/qtLwf3QZ)
[Source Code](https://pastebin.com/X1rJH111)

When I load the recipes from [https://mcasset.cloud/](https://mcasset.cloud/) everything works without any problems

**Comment by NightlandDriver** [comment]
Is there any idea where the error is?

**Comment by InventivetalentDev** [comment]
as for the weird rendering, the RP you're using is probably in a higher resolution and it renders as if it were mc's default dimensions. you can try using a lower-res version for now.

**Comment by NightlandDriver** [comment]
Well then I will convert the ResourcePack to a smaller resolution.
Would it be possible to add an option for scaling like for the inventory?
