### ISSUE TITLE
skin transparency not work

### ISSUE THREAD

**Issue by Nisutec** [InventivetalentDev/MineRender#105]
**Is your feature request related to a problem? Please describe.**
When I go to the Demo Site (https://minerender.org/demo/skin/#Niceattack) the Skin Viewer will not show the Skin correct. The Skin uses transparency on the second skin layer.

**Describe the solution you'd like**
Please add the possibility that the Skin Viewer can also display skins correctly with transparent elements.

**Comment by InventivetalentDev** [comment]
Should be fixed in v1.4.4
