### ISSUE TITLE
Is there a way to render both a skin and an item?

### ISSUE THREAD

**Issue by 1e4** [InventivetalentDev/MineRender#114]
Thank you for the library,

I was wondering if it's possible to render skins with items equipped? For example render a skin that is holding a diamond sword or wearing armor? I feel that it may be out of scope for this library but figured I'd ask before setting out to do it from scratch

**Comment by InventivetalentDev** [comment]
there is https://github.com/InventivetalentDev/MineRender/blob/master/src/combined/index.js which lets you to add different types  
see https://minerender.org/test/combined.html / https://github.com/InventivetalentDev/MineRender/blob/master/test/combined.html  

(also currently rewriting the library which will make that a bit less awkward)

**Comment by 1e4** [comment]
Hey! Thanks for the super fast reply, much appreciated. The combined seems to have a bug in which the diamond sword is floating in the example, not sure where it should be sitting.

I'm new to exploring how Minecraft works with it's rendering. I noticed things like the Bow for instance I can't find a 3d model for it. it seems that Minecraft may build what it looks like in game just from a png and a config file. My goal is figure out allowing people to equip armor/weapons/bow as a 3d model for example this https://mcasset.cloud/1.16.5/assets/minecraft/textures/item/diamond_sword.png works as an item in the inventory and floating on the floor as it's 2d, unsure of turning it into 3d as if it were equipped. Does that make sense?
