### ISSUE TITLE
Bedrock Edition 128x128 Skins

### ISSUE THREAD

**Issue by DaPigGuy** [InventivetalentDev/MineRender#12]
MineRender does not appear to support 128x128 skins (exclusive to Bedrock Edition). An example of a 128x128 skin: 
![image](https://user-images.githubusercontent.com/8540562/57988382-850a8480-7a42-11e9-9a1d-f4574db05404.png)
![jake](https://user-images.githubusercontent.com/8540562/57988384-86d44800-7a42-11e9-8911-1f663e61d0d0.png)

**Comment by InventivetalentDev** [comment]
Wasn't even aware these existed! Definitely going to look into adding support.
