### ISSUE TITLE
Its possible to export to a png file ?

### ISSUE THREAD

**Issue by xixi52** [InventivetalentDev/MineRender#120]
Hello youre project is awesome but its possible to export to a png file the skin with a pos ?

**Comment by pikachub2005** [comment]
To download a picture of the canvas, make a bookmarklet.
```
javascript: c = document.getElementsByTagName("canvas")[0]; a = document.createElement("a"); a.href = c.toDataURL(); a.download = "Minerender.png"; document.body.appendChild(a); a.click();
```
If you want to download the skin, try another site such as https://minecraft.tools/en/skin.php.
