### ISSUE TITLE
Capes in Embedded iFrame

### ISSUE THREAD

**Issue by bribes** [InventivetalentDev/MineRender#153]
**Is your feature request related to a problem? Please describe.**
Yes, I can't have a cape texture URL in the embedded iFrame of MineRender.

**Describe the solution you'd like**
I want to add `?cape=` parameter with a URL at the end.

**Describe alternatives you've considered**
Maybe `?capeUrl=` or `?cape_url=` instead?

**Additional context**
No.

**Comment by InventivetalentDev** [comment]
added support for that :) https://minerender.org/embed/skin/?skin.name=inventivetalent&cape.user=inventivetalent&cape=optifine

**Comment by bribes** [comment]
> added support for that :) https://minerender.org/embed/skin/?skin.name=inventivetalent&cape.user=inventivetalent&cape=optifine

Thank you!
