### ISSUE TITLE
How to enable animation or change player's pose?

### ISSUE THREAD

**Issue by Hukuta** [InventivetalentDev/MineRender#5]
I see animated demo on https://minerender.org/demo/skin/
but where is option to enable animation? here https://minerender.org/#getting-started

I found on demo skinRender event:

> document.body.addEventListener("skinRender", function (e) {    
>     var t = (Date.now() - startTime) / 1000;
>     e.detail.playerModel.children[2].rotation.x = Math.sin(t * 5) / 2;
>     e.detail.playerModel.children[3].rotation.x = -Math.sin(t * 5) / 2;
>     e.detail.playerModel.children[4].rotation.x = Math.sin(t * 5) / 2;
>     e.detail.playerModel.children[5].rotation.x = -Math.sin(t * 5) / 2;
> });

but when i'm rendering, this event never happens 

My code:

```
var skinRender = new SkinRender({
        /* options */
        autoResize: false,      // Whether to automatically resize the canvas
        controls: {
            enabled: false,      // Toggle controls
            zoom: false,         // Toggle zooming
            rotate: false,      // Toggle rotation
            pan: false           // Toggle panning
        },
        canvas: {               // Dimensions the canvas starts off with (undefined -> use window size)
            width: 400,
            height: 400
        },
        render: {
            taa: true
        },
        pauseHidden: false
    }, document.getElementById("mySkinContainer"));

var startTime = Date.now();

document.body.addEventListener("skinRender", function (e) {
    var t = (Date.now() - startTime) / 1000;
    e.detail.playerModel.children[2].rotation.x = Math.sin(t * 5) / 2;
    e.detail.playerModel.children[3].rotation.x = -Math.sin(t * 5) / 2;
    e.detail.playerModel.children[4].rotation.x = Math.sin(t * 5) / 2;
    e.detail.playerModel.children[5].rotation.x = -Math.sin(t * 5) / 2;

});

skinRender.render(skinURL);
```

Any idea why event "skinRender" never happens or how to modify playerModel?

**Comment by Hukuta** [comment]
I can animate like this:
```
var animate = function (t) {
    var p = skinRender.getPlayerModel();    
    p.children[2].rotation.x = Math.sin(t * 5) / 2;
    p.children[3].rotation.x = -Math.sin(t * 5) / 2;
    p.children[4].rotation.x = Math.sin(t * 5) / 2;
    p.children[5].rotation.x = -Math.sin(t * 5) / 2;
};
```

but still not clear why not work "skinRender" event

**Comment by InventivetalentDev** [comment]
Animation is not a native feature, you'll have to do it yourself - as you've already discovered - in the `skinRender` event.  
You will probably have to adjust the code from the demo, since that uses the body as the skin container. So something like `document.getElementById("mySkinContainer").addEventListener("skinRender" ...` should work :)

**Comment by Hukuta** [comment]
I have tested this too:
> document.getElementById("mySkinContainer").addEventListener("skinRender" ...

the same result - no event fired. 

Thanks for your answer.  I'm closing this issue
